### ISSUE TITLE
Some feature requests

### ISSUE THREAD

**Issue by Shuro** [Poke5555/C2-EB#2]
Here are some wishes, which probably also help to get this pack more popular:

- Add some mod to improve framerate:
I have an highend pc and the game is nearly unplayable. 30 FPS when i do nothing. Getting close to 1 frame after trying to break first tree. It needs optimization.

- Add the quest book:
Not everybody knows that you can access the quests in the inventory. I also didn't know, i had to bind the key and find out what to do. 

- Don't twerk for treegrowth:
I don't know how the mod was called, but there is an alternative to Twerk Sim 2k16 where you just hold crouch to grow trees, which is far less annoying than the whole spam button mechanic.

**Comment by Poke5555** [comment]
I'm not going to add and fps increasing because they cause compat issues with all kinds of stuff, if someone needs them they are able to add them themselves.

There is a sign on the wall that tells you quests are accessible in the top left of your inventory.

Twerk Sim 2K16 is in the pack so you actually have to do something in return for plant/tree growth (spamming crouch or running around) you can remove/add any mods you like. all you have to do is go into the profile options and uncheck the locked option.
